### PR TITLE
restore java 8

### PR DESCRIPTION
**Pull request by viqtor**

### CODE REVIEW

**Comment by viqtor** [comment]
follow up to https://github.com/dadoonet/elasticsearch-beyonder/discussions/181

**Comment by viqtor** [comment]
now thats just typical. "worked on my machine" 😉 
let me see if i would be able to reproduce and fix

**Review by dadoonet — APPROVED** [review]

**Comment by dadoonet** [comment]
Would you like to revisit your PR and make it support Java 8 again?

**Comment by viqtor** [comment]
> Would you like to revisit your PR and make it support Java 8 again?

sure. updated this pr to restore java 8 support

**Review by dadoonet — APPROVED** [review]
Thanks a lot!

**Comment by viqtor** [comment]
@dadoonet you think this warrants a release? would be nice to have the new features with component templates and pipelines on a <jdk14 relase

**Comment by dadoonet** [comment]
It does indeed. I'll try to get this out in the next hours.

**Comment by dadoonet** [comment]
I just made the release. Thanks for the ping and the PR @viqtor ;) 

https://discuss.elastic.co/t/announcement-elasticsearch-beyonder-7-13-2-released/279379

Please wait a bit until it's available on maven central.

**Pull request merged**
