### PR TITLE
Env var replacement

### PR DESCRIPTION
**Pull request by nilskuhn**
Environment variables get substituted in settings json files.

### CODE REVIEW

**Comment by dadoonet** [comment]
Looks amazing!

**Comment by nilskuhn** [comment]
What is your releasing schedule? I would like to use this asap as a maven dependency. Any plans for version 7.1?

**Comment by dadoonet** [comment]
I just released a 7.5 version. It will require some minutes/hours to have it on Maven Central I think but we should be OK.

Thanks!

**Comment by nilskuhn** [comment]
Great! 
Thanks for the fast response and release :)

**Pull request merged**
